### ISSUE TITLE
Upgrade to pac4j 2.0 SNAPSHOT 

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/spring-webmvc-pac4j#9]
```

java.lang.NoClassDefFoundError: org/pac4j/core/engine/ApplicationLogoutLogic

	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at org.springframework.util.ReflectionUtils.getDeclaredFields(ReflectionUtils.java:715)
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:687)
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:673)
	at org.springframework.boot.test.mock.mockito.DefinitionsParser.parse(DefinitionsParser.java:63)
	at org.springframework.boot.test.mock.mockito.MockitoPostProcessor.postProcessBeanFactory(MockitoPostProcessor.java:141)
	at org.springframework.boot.test.mock.mockito.MockitoPostProcessor.postProcessBeanFactory(MockitoPostProcessor.java:133)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:281)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:169)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:686)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:524)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:111)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:98)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:116)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:83)
	at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:189)
	at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:131)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:230)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:228)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:287)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:289)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:247)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.ClassNotFoundException: org.pac4j.core.engine.ApplicationLogoutLogic
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 48 more
```

**Comment by leleuj** [comment]
It's a work in progress, but it should be ok now.

**Comment by mmoayyed** [comment]
Another breaking change:

```
Caused by:
                    org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.pac4j.springframework.web.CallbackController]: Factory method 'callbackController' threw exception; nested exception is java.lang.NoClassDefFoundError: org/pac4j/core/engine/J2ERenewSessionCallbackLogic
                        Caused by:
                        java.lang.NoClassDefFoundError: org/pac4j/core/engine/J2ERenewSessionCallbackLogic
```

**Comment by leleuj** [comment]
This class has been removed in pac4j and thus in spring-webmvc-pac4j (https://github.com/pac4j/spring-webmvc-pac4j/blob/master/src/main/java/org/pac4j/springframework/web/CallbackController.java#L32): this error should not happen. Are you sure you're up-to-date?

**Comment by SimonJames-imanage** [comment]
Regarding the J2ERenewSessionCallbackLogic NoClassDefFoundError exception, I am still getting this when trying to use pac4j 2.0.0 jars with the latest spring-security-pac4j (2.1.2). 
Specifically, I can see that the CallbackFilter class in spring-security-pac4j references J2ERenewSessionCallbackLogic . 
Can you clarify whether I should be able to use 2.0.0 with CallbackFilters?
Thanks.

**Comment by leleuj** [comment]
There is a confusion here between: `spring-webmvc-pac4j` and `spring-security-pac4j`.

The first library has been upgraded to use pac4j v2.0.0, not the second one. So if you use `spring-security-pac4j`,  you must stay with pac4j 1.9.7 for a few weeks more.

**Comment by andrew-boutin** [comment]
Is there any update on when `spring-security-pac4j` will be updated so that we can use `pac4j-core:2.0.0`?

**Comment by leleuj** [comment]
Sure. Take a look: the incoming version 3.0.0-SNAPSHOT of `spring-security-pac4j` is already based on `pac4j` v2.1.0-SNAPSHOT: https://github.com/pac4j/spring-security-pac4j/blob/master/pom.xml#L59

Both releases (`pac4j` and `spring-security-pac4j`) will come very soon: this week or next one...
